# Permalinks
permalink:        /post/:title.html

# Setup
url:              https://rhl7168.github.io
img_url:          https://rhl7168.github.io/img.github.io/image

# Set to '' in case of hosting on `https://<your-github-name>.github.io`
baseurl:          ''

title:            '一粒小小小精灵'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  [学无止境尚需专注弥坚](https://rhl7168.github.io/code/)

# Google Analytics tracking ID
# analytics:        'UA-32028925-2'

# Fallback image and color if not overwritten for tag or post
image:            /public/images/hedin.jpg
color:            '#dc322f'

author:
  name:           '一粒小小小精灵'
  email:          l_renhailing@163.com
  github:         rhl7168
  photo:          /public/images/pic.png


  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    我是一粒小小小精灵，热爱工作，热爱编程的女程序媛，永远向着未来，向着光芒努力！


compress_html:
  clippings:      all
  comments:       ["<!--", "-->"]
  endings:        all
  startings:      [html, head, body]

sass:
  sass_dir:       /public/css
  style:          compressed
